### ISSUE TITLE
Edit function example introducing unreachable statement in wasm

### ISSUE THREAD

**Issue by Skid000** [Qwokka/WAIL#2]
When the example edit function example runs it creates an unreachable statement within the wasm.

WAIL edited wasm below.
`(module
  (func $changeMe (;0;) (export "changeMe") (result i32)
    unreachable
    i32.const 1337
    return
  )
)`
Is this intentional?

**Comment by Qwokka** [comment]
Oops, good catch! This should be fixed with 41c655434da60f14dfda88813b0cef9000c79ca6

Thanks!
Jack

**Comment by Skid000** [comment]
No problem!
Thank you for fixing it
